### ISSUE TITLE
build failed on 64-bit system

### ISSUE THREAD

**Issue by vanloswang** [netfoundry/zfw#82]
zfw_tc_ingress.c:3117:5 error: looks like the BPF stack limit of 512 bytes is exceeded. Please move large on stack variables into BPF per-cpu array map 
int bpf_sk_splice5( struct __sk_buff *skb){

**Comment by r-caamano** [comment]
Hi @vanloswang thanks for reporting your issue. Can you please share more details on the platform you are attempting to build on i.e. what linux distro/version, kernel version , libbpf version etc.  Our packages are built on 64 bit systems (Ubuntu 22.04 amd64 and arm64) and we cannot reproduce the issue you are reporting.  Example output from build on ubuntu 22.04 amd64

```
Linux ebpf-router 5.15.0-124-generic #134-Ubuntu SMP Fri Sep 27 20:20:17 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
ziggy@ebpf-router:~$ mkdir ~/repos
cd repos
git clone https://github.com/netfoundry/zfw.git
cd zfw/src
make all
sudo make install ARGS=router
Cloning into 'zfw'...
remote: Enumerating objects: 2646, done.
remote: Counting objects: 100% (980/980), done.
remote: Compressing objects: 100% (336/336), done.
remote: Total 2646 (delta 698), reused 831 (delta 626), pack-reused 1666 (from 1)
Receiving objects: 100% (2646/2646), 991.36 KiB | 5.11 MiB/s, done.
Resolving deltas: 100% (1526/1526), done.
clang -D BPF_MAX_ENTRIES=100000 -O1 -lbpf -o zfw  zfw.c
clang  -O1 -lbpf -o zfw_monitor  zfw_monitor.c
clang -D BPF_MAX_ENTRIES=100000 -g -O2 -Wall -W extra -target bpf -c zfw_tc_ingress.c -o zfw_tc_ingress.o
clang -O2 -g -Wall -target bpf -c zfw_xdp_tun_ingress.c -o zfw_xdp_tun_ingress.o
clang -D BPF_MAX_ENTRIES=100000 -g -O2 -Wall -Wextra -target bpf -c -o zfw_tc_outbound_track.o zfw_tc_outbound_track.c
clang -o zfw_tunnwrapper zfw_tunnel_wrapper.c -l json-c
./install.sh router
ziggy@ebpf-router:~/repos/zfw/src$ sudo zfw -V
0.9.2
ziggy@ebpf-router:~/repos/zfw/src$ sudo zfw -X ens33 -O /opt/openziti/bin/zfw_tc_ingress.o -z ingress
Set tc filter enable to 1 for ingress on ens33
```

**Comment by vanloswang** [comment]
@r-caamano I have tried CentOS 8.2 and 8.5, both of them report BPF stack limit issuw, and successed on anolios 8 with kernel 5.10. so we should fix the build on CentOS 8.2 and 8.5 with x86_64 version. CentOS 8.2 and 8.5 with kernel 4.18 and libbpf 0.6.

**Comment by r-caamano** [comment]
Hi @vanloswang 4.18 lacks support for some of the core EBPF functions that are utilized in zfw.  Also Centos 8 reached end of life 3 years ago.  So at this time we are not planning to backport to support Centos 8/Kernel 4.18.

**Comment by vanloswang** [comment]
@r-caamano What is the minimum kernel version requirement for zfw?
